### ISSUE TITLE
Failed validation: #/definitions/QuoteSummaryResult (yahooFinanceType)

### ISSUE THREAD

**Issue by matthewmuscat** [gadicc/node-yahoo-finance2#461]
# Validation Error

## Minimal Reproduction

The array being mapped, below, can have hundreds of objects (tickers) at one given time. I am not sure if this may have an affect on this but I wouldn't think so?
```javascript
await Promise.all(
  [{ symbol: "EQS"}].map(async (ann) => {
    const tickerData = await yahooFinance.quoteSummary(
       `${ann.symbol}.AX`, // ASX
       { modules: ["price", "summaryDetail", "summaryProfile", "financialData"] }
    )

    const additionalFields = {
       name: tickerData.price?.longName,
       price: tickerData.financialData?.currentPrice,
       volume: tickerData.summaryDetail?.averageVolume,
       marketCap: tickerData.summaryDetail?.marketCap,
       sector: tickerData.summaryProfile?.sector,
    }
    return { ...ann, ...additionalFields }
  })
)
```
## Symbol(s) that it happened for
- EQS.AX
- YRL.AX
- G79.AX
- APS.AX

## Error Message

For most errors, I found it spammed a lot of errors in this format:
```
    {..},
    ... (at least a dozen more here)
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'date', did you want 'date | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/startDate',
      schemaPath: '#/definitions/SummaryDetail/properties/startDate/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'date', did you want 'date | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/expireDate',
      schemaPath: '#/definitions/SummaryDetail/properties/expireDate/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/openInterest',
      schemaPath: '#/definitions/SummaryDetail/properties/openInterest/yahooFinanceType',
      data: {}
    }
```

I managed to find one ticker (APS.AX) that didn't "spam", and have provided the entire error here:
```
FailedYahooValidationError: Failed Yahoo Schema validation
    at validate (node_modules/yahoo-finance2/dist/cjs/src/lib/validateAndCoerceTypes.js:286:15)
    at Object.<anonymous> (node_modules/yahoo-finance2/dist/cjs/src/lib/moduleExec.js:96:53)
    at Generator.next (<anonymous>)
    at fulfilled (node_modules/yahoo-finance2/dist/cjs/src/lib/moduleExec.js:21:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  result: {
    summaryDetail: {
      ... valid stuff
    },
    summaryProfile: {
      ... valid stuff
    },
    price: {
      ... valid stuff
    },
    financialData: {
      ... valid stuff
    }
  },
  errors: [
    {
      instancePath: '/summaryDetail',
      schemaPath: '#/definitions/SummaryDetail/required',
      keyword: 'required',
      params: [Object],
      message: "must have required property 'previousClose'",
      data: [Object]
    },
    {
      instancePath: '/summaryDetail',
      schemaPath: '#/definitions/SummaryDetail/required',
      keyword: 'required',
      params: [Object],
      message: "must have required property 'regularMarketPreviousClose'",
      data: [Object]
    }
  ]
}
```

## Environment
Browser or Node:  Node (Serverless Lambda)
Node version (if applicable): 14.x
Npm version: 
Browser verion (if applicable):
Library version (e.g. `1.10.1`): 

## Additional Context
This is being executed in a Serverless Node.js function.

**Comment by gadicc** [comment]
Hey @matthewmuscat, thanks for reporting, and sifting through all the relevant info for us.

It looks like the first few symbols you gave are returning a `quoteType` of `"NONE"`; from our experience this usually means that the symbol has been delisted and Yahoo no longer has any information for it.  I'm considering how to best handle this case, probably by returning the same error for unlisted (rather than delisted) symbols, to make it consistent.  I'm out of time for today but will keep you posted.

I'll also fix up the errors on `APS.AX`.

Thanks again for reporting.

**Comment by gadicc** [comment]
Releasing the fixes for `APS.AX` in the meantime... you'll get an automated message here when that happens.  Keeping the issue open until we handle the `quoteType: "NONE"` symbols better.

**Comment by matthewmuscat** [comment]
> Thanks again for reporting.

Thanks for your speedy support. I believe this is happening for a LOT of tickers. I will run a few tests and see if I can come up with a counter.

I also had a few questions if you wouldn't mind clarifying for me? 

Is there rate limiting / is there a maximum number of requests I can make a day?

Cheers

**Comment by matthewmuscat** [comment]
@gadicc So this is an updated list of the tickers that Yahoo did not work for. I don't imagine anything can be done about this?

```javascript
['ZOR', 'LRD', 'RAB', 'SEL', 'G79', 'ADE', 'AAA', 'BND', 'MST', 'YTM', 'AUM', 'CTW', 'IHW', 'DHO', 'SNX', 'KOB', 'EQS', 'FLO', 'FHE', 'PCI', 'VTS', 'TOV', 'SLS', 'RF1', 'BRX', 'IMP', 'KKC', 'EIG', 'VG8', 'TA1', 'STW', 'SLF', 'SFY']
```
