### ISSUE TITLE
Failed validation: #/definitions/OptionsResult

### ISSUE THREAD

**Issue by Lexus2016** [gadicc/node-yahoo-finance2#560]
# Validation Error

## Symbol(s) that it happened for
EBAY

## Error Message

(node:59078) UnhandledPromiseRejectionWarning: FailedYahooValidationError: Failed Yahoo Schema validation
    at validate (/Users/admin/Documents/_Projects/SeasonPatterns/back/node_modules/yahoo-finance2/dist/cjs/src/lib/validateAndCoerceTypes.js:298:15)
    at Object.<anonymous> (/Users/admin/Documents/_Projects/SeasonPatterns/back/node_modules/yahoo-finance2/dist/cjs/src/lib/moduleExec.js:96:53)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/admin/Documents/_Projects/SeasonPatterns/back/node_modules/yahoo-finance2/dist/cjs/src/lib/moduleExec.js:21:58)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:59078) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:59078) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

## Environment
Browser or Node: 
Node version (if applicable): v14.17.1
Npm version: 8.19.2
Browser verion (if applicable):
Library version (e.g. `1.10.1`):  2.3.7

**Comment by gadicc** [comment]
Thanks for reporting, @Lexus2016.  I believe this is fixed now, it's building now in CI and there'll be an automated message here with the new version when it's ready for use.  I'll leave the issue open until you can confirm the same.

**Comment by gadicc** [comment]
Great!  Thanks!
