### ISSUE TITLE
Failed validation: #/definitions/QuoteSummaryResult

### ISSUE THREAD

**Issue by Lexus2016** [gadicc/node-yahoo-finance2#562]
# Validation Error

## Symbol(s) that it happened for
AVO
AUR

## Error Message
The following result did not validate with schema: #/definitions/QuoteSummaryResult
[
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/price/volume24Hr',
    schemaPath: '#/definitions/Price/properties/volume24Hr/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/price/volumeAllCurrencies',
    schemaPath: '#/definitions/Price/properties/volumeAllCurrencies/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/price/circulatingSupply',
    schemaPath: '#/definitions/Price/properties/circulatingSupply/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/trailingAnnualDividendRate',
    schemaPath: '#/definitions/SummaryDetail/properties/trailingAnnualDividendRate/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/trailingAnnualDividendYield',
    schemaPath: '#/definitions/SummaryDetail/properties/trailingAnnualDividendYield/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/yield',
    schemaPath: '#/definitions/SummaryDetail/properties/yield/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/totalAssets',
    schemaPath: '#/definitions/SummaryDetail/properties/totalAssets/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/navPrice',
    schemaPath: '#/definitions/SummaryDetail/properties/navPrice/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/ytdReturn',
    schemaPath: '#/definitions/SummaryDetail/properties/ytdReturn/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/volume24Hr',
    schemaPath: '#/definitions/SummaryDetail/properties/volume24Hr/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/volumeAllCurrencies',
    schemaPath: '#/definitions/SummaryDetail/properties/volumeAllCurrencies/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/circulatingSupply',
    schemaPath: '#/definitions/SummaryDetail/properties/circulatingSupply/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'date', did you want 'date | null' ?",
    params: { schema: 'date', data: {} },
    instancePath: '/summaryDetail/startDate',
    schemaPath: '#/definitions/SummaryDetail/properties/startDate/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'date', did you want 'date | null' ?",
    params: { schema: 'date', data: {} },
    instancePath: '/summaryDetail/expireDate',
    schemaPath: '#/definitions/SummaryDetail/properties/expireDate/yahooFinanceType',
    data: {}
  },
  {
    keyword: 'yahooFinanceType',
    message: "Got {}->null for 'number', did you want 'number | null' ?",
    params: { schema: 'number', data: {} },
    instancePath: '/summaryDetail/openInterest',
    schemaPath: '#/definitions/SummaryDetail/properties/openInterest/yahooFinanceType',
    data: {}
  }
]

This may happen intermittently and you should catch errors appropriately.
However:  1) if this recently started happening on every request for a symbol
that used to work, Yahoo may have changed their API.  2) If this happens on
every request for a symbol you've never used before, but not for other
symbols, you've found an edge-case (OR, we may just be protecting you from
"bad" data sometimes stored for e.g. misspelt symbols on Yahoo's side).
Please see if anyone has reported this previously:

  https://github.com/gadicc/node-yahoo-finance2/issues?q=is%3Aissue+Failed%20validation%3A%20%23%2Fdefinitions%2FQuoteSummaryResult

or open a new issue (and mention the symbol):  yahoo-finance2 v2.3.10

  https://github.com/gadicc/node-yahoo-finance2/issues/new?labels=bug%2C+validation&template=validation.md&title=Failed%20validation%3A%20%23%2Fdefinitions%2FQuoteSummaryResult

For information on how to turn off the above logging or skip these errors,
see https://github.com/gadicc/node-yahoo-finance2/tree/devel/docs/validation.md.

FailedYahooValidationError: Failed Yahoo Schema validation
    at validate (/home/ubuntu/1/node_modules/yahoo-finance2/dist/cjs/src/lib/validateAndCoerceTypes.js:298:15)
    at Object.<anonymous> (/home/ubuntu/1/node_modules/yahoo-finance2/dist/cjs/src/lib/moduleExec.js:96:53)
    at Generator.next (<anonymous>)
    at fulfilled (/home/ubuntu/1/node_modules/yahoo-finance2/dist/cjs/src/lib/moduleExec.js:21:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5) {
  result: {
    summaryDetail: {
      maxAge: 1,
      priceHint: 4,
      previousClose: 1.86,
      open: 1.88,
      dayLow: 1.7315,
      dayHigh: 1.88,
      regularMarketPreviousClose: 1.86,
      regularMarketOpen: 1.88,
      regularMarketDayLow: 1.7315,
      regularMarketDayHigh: 1.88,
      payoutRatio: 0,
      forwardPE: -0.6122807,
      volume: 717318,
      regularMarketVolume: 717318,
      averageVolume: 2556320,
      averageVolume10days: 2587890,
      averageDailyVolume10Day: 2587890,
      bid: 1.75,
      ask: 1.76,
      bidSize: 1800,
      askSize: 3000,
      marketCap: 1961345152,
      yield: {},
      ytdReturn: {},
      totalAssets: {},
      expireDate: {},
      strikePrice: {},
      openInterest: {},
      fiftyTwoWeekLow: 1.57,
      fiftyTwoWeekHigh: 17.77,
      priceToSalesTrailing12Months: 13.5014715,
      fiftyDayAverage: 2.2627,
      twoHundredDayAverage: 3.33635,
      trailingAnnualDividendRate: {},
      trailingAnnualDividendYield: {},
      navPrice: {},
      currency: 'USD',
      fromCurrency: null,
      lastMarket: null,
      volume24Hr: {},
      volumeAllCurrencies: {},
      circulatingSupply: {},
      algorithm: null,
      maxSupply: {},
      startDate: {},
      tradeable: false
    },
    defaultKeyStatistics: {
      maxAge: 1,
      priceHint: 4,
      enterpriseValue: 1146956928,
      forwardPE: -2.2371795,
      profitMargins: 0,
      floatShares: 321050437,
      sharesOutstanding: 642870016,
      sharesShort: 13164998,
      sharesShortPriorMonth: 1970-06-08T23:54:11.000Z,
      sharesShortPreviousMonthDate: 2022-09-15T00:00:00.000Z,
      dateShortInterest: 2022-10-14T00:00:00.000Z,
      sharesPercentSharesOut: 0.0114,
      heldPercentInsiders: 0.56435,
      heldPercentInstitutions: 0.47471002,
      shortRatio: 6.17,
      shortPercentOfFloat: 0.032,
      category: null,
      bookValue: 1.157,
      priceToBook: 1.508211,
      fundFamily: null,
      legalType: null,
      lastFiscalYearEnd: 2021-12-31T00:00:00.000Z,
      nextFiscalYearEnd: 2023-12-31T00:00:00.000Z,
      mostRecentQuarter: 2022-06-30T00:00:00.000Z,
      netIncomeToCommon: -1616007040,
      trailingEps: -2.686,
      forwardEps: -2.85,
      lastSplitFactor: null,
      enterpriseToRevenue: 7.895,
      enterpriseToEbitda: -1.656
    },
    price: {
      maxAge: 1,
      preMarketChangePercent: 0,
      preMarketChange: 0,
      preMarketTime: 2022-11-16T14:12:01.000Z,
      preMarketPrice: 1.86,
      preMarketSource: 'DELAYED',
      regularMarketChangePercent: -0.06182796,
      regularMarketChange: -0.11500001,
      regularMarketTime: 2022-11-16T16:43:05.000Z,
      priceHint: 4,
      regularMarketPrice: 1.745,
      regularMarketDayHigh: 1.88,
      regularMarketDayLow: 1.7315,
      regularMarketVolume: 717318,
      averageDailyVolume10Day: 2587890,
      averageDailyVolume3Month: 2556320,
      regularMarketPreviousClose: 1.86,
      regularMarketSource: 'FREE_REALTIME',
      regularMarketOpen: 1.88,
      exchange: 'NMS',
      exchangeName: 'NasdaqGS',
      exchangeDataDelayedBy: 0,
      marketState: 'REGULAR',
      quoteType: 'EQUITY',
      symbol: 'AUR',
      underlyingSymbol: null,
      shortName: 'Aurora Innovation, Inc.',
      longName: 'Aurora Innovation, Inc.',
      currency: 'USD',
      quoteSourceName: 'Nasdaq Real Time Price',
      currencySymbol: '$',
      fromCurrency: null,
      lastMarket: null,
      volume24Hr: {},
      volumeAllCurrencies: {},
      circulatingSupply: {},
      marketCap: 1961345152
    }
  },
  errors: [
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/price/volume24Hr',
      schemaPath: '#/definitions/Price/properties/volume24Hr/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/price/volumeAllCurrencies',
      schemaPath: '#/definitions/Price/properties/volumeAllCurrencies/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/price/circulatingSupply',
      schemaPath: '#/definitions/Price/properties/circulatingSupply/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/trailingAnnualDividendRate',
      schemaPath: '#/definitions/SummaryDetail/properties/trailingAnnualDividendRate/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/trailingAnnualDividendYield',
      schemaPath: '#/definitions/SummaryDetail/properties/trailingAnnualDividendYield/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/yield',
      schemaPath: '#/definitions/SummaryDetail/properties/yield/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/totalAssets',
      schemaPath: '#/definitions/SummaryDetail/properties/totalAssets/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/navPrice',
      schemaPath: '#/definitions/SummaryDetail/properties/navPrice/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/ytdReturn',
      schemaPath: '#/definitions/SummaryDetail/properties/ytdReturn/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/volume24Hr',
      schemaPath: '#/definitions/SummaryDetail/properties/volume24Hr/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/volumeAllCurrencies',
      schemaPath: '#/definitions/SummaryDetail/properties/volumeAllCurrencies/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/circulatingSupply',
      schemaPath: '#/definitions/SummaryDetail/properties/circulatingSupply/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'date', did you want 'date | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/startDate',
      schemaPath: '#/definitions/SummaryDetail/properties/startDate/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'date', did you want 'date | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/expireDate',
      schemaPath: '#/definitions/SummaryDetail/properties/expireDate/yahooFinanceType',
      data: {}
    },
    {
      keyword: 'yahooFinanceType',
      message: "Got {}->null for 'number', did you want 'number | null' ?",
      params: [Object],
      instancePath: '/summaryDetail/openInterest',
      schemaPath: '#/definitions/SummaryDetail/properties/openInterest/yahooFinanceType',
      data: {}
    }
  ]
}

## Environment
Browser or Node: 
Node version (if applicable):  v14.20.1
Npm version: 9.1.1
Browser verion (if applicable):
Library version (e.g. `1.10.1`):  2.3.10

**Comment by gadicc** [comment]
Thanks for another report @Lexus2016.  Is this still happening for you?  I can't currently reproduce it (yahoo-finance can be finicky like that, exactly why we do so much validation).

If you can still reproduce this, and would be interested in performing some further tests and sending me the results, let me know, and I'll outline the process.  (This is only necessary because I can't reproduce my side).

As a last resort, I could try a fix based on the error messages a lone but I prefer not publishing untested code, also, this could have been a temporary issue with yahoo.

**Comment by Lexus2016** [comment]
@gadicc I agree. There is no problem today. Tnx!
