### ISSUE TITLE
Problem fetching quotes, "unsupported redirect"

### ISSUE THREAD

**Issue by shaneikennedy** [gadicc/node-yahoo-finance2#777]
# Bug Report

## Describe the bug
```
Please consider completing the survey at https://bit.ly/yahoo-finance-api-feedback if you haven't already; for more info see https://github.com/gadicc/node-yahoo-finance2/issues/764#issuecomment-2056623851.
09:38:27.142 Fetching crumb and cookies from https://finance.yahoo.com/quote/AAPL...
09:38:27.361 fetch https://guce.yahoo.com/consent?brandType=nonEu&gcrumb=UjqZDCU&done=https%3A%2F%2Ffinance.yahoo.com%2Fquote%2FAAPL
09:38:27.706 fetch https://consent.yahoo.com/v2/collectConsent?sessionId=3_cc-session_33add8e1-9cbf-429f-b0aa-bc0e5896c57b
09:38:28.093 fetch https://consent.yahoo.com/v2/collectConsent?sessionId=3_cc-session_33add8e1-9cbf-429f-b0aa-bc0e5896c57b
09:38:28.184 fetch https://guce.yahoo.com/copyConsent?sessionId=3_cc-session_33add8e1-9cbf-429f-b0aa-bc0e5896c57b&lang=sv-SE
09:38:28.268 Fetching crumb and cookies from https://finance.yahoo.com/quote/AAPL?guccounter=1...
09:38:28.355 Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.
    at _getCrumb (/Users/shane.kennedy/.config/raycast/extensions/quotes/index.js:27889:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _getCrumb (/Users/shane.kennedy/.config/raycast/extensions/quotes/index.js:27886:16)
09:38:28.355 Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.
    at _getCrumb (/Users/shane.kennedy/.config/raycast/extensions/quotes/index.js:27889:13)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async _getCrumb (/Users/shane.kennedy/.config/raycast/extensions/quotes/index.js:27886
```

## Minimal Reproduction
`await yahooFinance.quote('AAPL')`

## Environment
Browser or Node: 
Node version (if applicable): 20.12.0
Npm version: 10.5.0
Library version (e.g. `1.10.1`): "yahoo-finance2": "^2.11.0"

**Comment by dinhminhx** [comment]
Same issue here

**Comment by gadicc** [comment]
Hey all, thanks for reporting.

I've released a workaround for this.  Instead of failing, it will just log and continue, and everything seems to be working fine -- for now.  However, it looks like Yahoo are in the middle of some changes and things may well break again soon.  So please do report any further breakages.

:pray:

**Comment by shaneikennedy** [comment]
@gadicc Thanks for this project and constantly going to war with yahoo for us all 🫡

**Comment by gadicc** [comment]
For sure, my pleasure.  Definitely not going to war against Yahoo though 😅  Have made a lot of effort to make sure the library "plays nice" with their services and team, and so far so good 🙏

**Comment by Abudibro** [comment]
This is no longer working again, not sure if this is an issue on my end or not

```
Fetching crumb and cookies from https://finance.yahoo.com/quote/AAPL?guccounter=1...
Error: Unsupported redirect to https://finance.yahoo.com/quote/AAPL/, please report.
    at _getCrumb (/Users/abdurahmanhijazi/dev/stock-option-screener/netlify/node_modules/yahoo-finance2/dist/esm/src/lib/getCrumb.js:130:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at _getCrumb (/Users/abdurahmanhijazi/dev/stock-option-screener/netlify/node_modules/yahoo-finance2/dist/esm/src/lib/getCrumb.js:126:24)
    at Object.yahooFinanceFetch [as _fetch] (/Users/abdurahmanhijazi/dev/stock-option-screener/netlify/node_modules/yahoo-finance2/dist/esm/src/lib/yahooFinanceFetch.js:53:23)
    at Object.moduleExec [as _moduleExec] (/Users/abdurahmanhijazi/dev/stock-option-screener/netlify/node_modules/yahoo-finance2/dist/esm/src/lib/moduleExec.js:52:18)
    at /Users/abdurahmanhijazi/dev/stock-option-screener/netlify/functions/quote.js:19:25
Response with status 304 in 1089 ms.
```

**Comment by gadicc** [comment]
@Abudibro, for what query?  I tried with `quote("AAPL")` and it works.

From time to time there are issues with Yahoo's servers that can cause issues like this.  They usually resolve themselves within a few hours, with no action on our part.

What country are you in?  Sometimes these issues are region-specific (as it only affects servers in one region).  You could try a VPN to change countries and see if it makes any difference (try somewhere far away, e.g. US vs EU vs EMEA etc).

If you do find an issue specific to a region, and one that doesn't resolve itself within a day or so, unfortunately I won't have a chance to look into this further until next week :/

**Comment by Abudibro** [comment]
@gadicc The bug is happening for the `quote` function yeah. I am in the same country as you, UK. So it can't be a region thing. 

The strange thing is that other ones work, for example the `suggestion` function works as normal but the `quote` one is giving me issues.

If I find out what the issue is I'll post it here, maybe it'll save someone else in the future some headache lol
